// The film's script: one source for the player, captions, storyboard and export.
// Times are in seconds. Each voiceover line is paired with the action it names.
window.FILM = {
  title: 'Parmis & Orange',
  duration: 90,
  fps: 12, // paper-cut stop-motion, "on twos" at 24fps
  scenes: [
    {
      id: 'child', n: 1, stage: 'Age 7', start: 0, end: 9,
      title: 'A child learning English',
      image: 'Blank paper. The small orange shape drops in and stamps the title, then hops into a notebook. The classroom is built in paper pieces around me, age seven, perched on a stool in the middle with my notebook. My mother stands at the board — seen from a child’s height, so only her cardigan, her arm and the chalk are in frame. Classmates sit at desks either side.',
      dress: 'Children’s book pages, bright magazine scraps, crayon drawings, small alphabet tiles. My face is cut from my own childhood photo, flowers in my hair.',
      movement: 'Chalk letters appear stroke by stroke. Alphabet tiles lift off the board and flutter onto my notebook and dress. The orange shape lands on the notebook page as a doodle.',
      transition: 'I lift the notebook over my head. Its page opens and unfolds into the hand-cut “Orange” sign.',
      text: ['Parmis & Orange', 'age 7 · my mother’s English class', 'Board: A a  B b  C c'],
    },
    {
      id: 'orange', n: 2, stage: 'Age 12', start: 9, end: 17,
      title: 'Orange begins',
      image: 'The classroom falls away and a paper school front builds itself. I am twelve, a little taller, in front of the door. My mother’s hands reach in from above the frame to hang the sign. A paper-doll chain in the window stands for family.',
      dress: 'Classroom posters, lesson sheets and orange paper pasted over the book pages. Still my childhood photo, a little taller; my face at twenty arrives in chapter 3.',
      movement: 'The sign unfolds in three stop-motion steps. Hands hang it, then leave. Posters pin themselves to the walls. New patches paste over my dress one by one.',
      transition: 'A lesson sheet peels off the wall, spins towards the camera and becomes the whiteboard behind me.',
      text: ['Orange · Language Institute', 'age 12 · my mother opens Orange', 'My mother’s school. Our family’s story.'],
    },
    {
      id: 'teacher', n: 3, stage: 'University', start: 17, end: 25.7,
      title: 'Teaching at Orange, at university',
      image: 'An Orange classroom. I stand at the whiteboard as a university student and teacher. Four children of about ten sit at desks on both sides.',
      dress: 'Classroom notes, sticky notes, worksheets with ticks and stars. A pencil tucked behind my ear. My face is from a photo of me at twenty.',
      movement: 'I hold up a picture card. Hands shoot up; speech bubbles pop. A paper magnifier sweeps across the class, and above each child a small bubble shows how they learn: pictures, sounds, hands, talk.',
      transition: 'A child’s worksheet folds, step by step, into a paper cube that drops to the floor.',
      text: ['university years · teaching at Orange', 'Hello, class!', 'Watching how they learn.'],
    },
    {
      id: 'early', n: 4, stage: 'Training', start: 25.7, end: 35.2,
      title: 'Montessori, then phonics',
      image: 'The cube lands as the first block of a pink tower in a child-sized room: low shelf, bead bars, sandpaper letters, tiny chairs. I kneel at child height between two small children. Then a sandpaper letter lifts off and the room fills with letters and sounds.',
      dress: 'Wood grain, bead bars and sandpaper letters, then phonics letters, sound marks and word pieces as the main pattern.',
      movement: 'Small hands stack the tower block by block. Letter tiles s · a · t pop up with their sounds, slide together into “sat”, and flutter onto my dress.',
      transition: 'The room folds shut like a book, into the frame of a computer monitor.',
      text: ['training · Montessori', 'training · phonics', 's · a · t → sat'],
    },
    {
      id: 'online', n: 5, stage: 'COVID', start: 35.2, end: 45,
      title: 'Teaching during COVID',
      image: 'Inside the monitor: a video-call grid. I am in the middle tile with a headset. From here on my face is from my current portrait. Six children in paper webcam frames wave, clap, hold up cards and raise their hands.',
      dress: 'Phonics cards, lesson slides, webcam frames and little paper windows.',
      movement: 'I flip phonics cards, sing (paper notes rise), and a sock puppet says hi. Each child answers in their own way; one holds up a card to match mine.',
      transition: 'The lesson slide swells to fill the screen.',
      text: ['COVID · teaching online', 'b · ball · bee', 'Keeping little learners close.'],
    },
    {
      id: 'question', n: 6, stage: 'The question', start: 45, end: 52.8,
      title: 'The design question',
      image: 'I stand in front of the big slide. Tiny toolbar buttons crowd its edge. A pencil circles one; a paper question mark pops over my head. Then the slide opens like two doors into an imagined learning platform.',
      dress: 'Pencil sketches, buttons, feedback sticky notes, stars and drag handles.',
      movement: 'Interface pieces fly out and arrange around me: big buttons, picture cards, letter tiles, a read-aloud speaker. The orange shape becomes the big “play” button.',
      transition: 'The monitor rounds its corners into an airplane window.',
      text: ['the design question', 'bigger buttons · read it aloud · fewer clicks', 'What if the screen were built for them?'],
    },
    {
      id: 'canada', n: 7, stage: 'Canada', start: 52.8, end: 62.6,
      title: 'Canada and BrainStation',
      image: 'An airplane window with paper clouds; the orange shape is the sun. I hold a suitcase with a maple-leaf tag. Then the window becomes a capstone wall: research notes, a simple flow, accessibility reminders and early screens, tied by orange thread to a phonics card and a worksheet from my teaching years.',
      dress: 'Research notes, simple flows, accessibility reminders and early interface sketches.',
      movement: 'Clouds slide past in steps. A maple leaf drifts down. Sticky notes slap onto the wall; thread stretches from the old classroom pieces to the new notes.',
      transition: 'One sticky note grows into a speech bubble.',
      text: ['Canada · BrainStation', 'children’s needs · teacher pain points', 'Capstone: a teaching platform for young children.'],
    },
    {
      id: 'volante', n: 8, stage: 'Volante', start: 62.6, end: 70.2,
      title: 'A new design career',
      image: 'A calm studio. I talk with users; their speech bubbles surround me. Accessibility pieces — contrast, captions, keyboard, access symbol — pin up behind. A thin orange paper thread runs through the background, with the small shape tied to it.',
      dress: 'User research, conversation bubbles, accessibility symbols, “equal access” tags.',
      movement: 'Bubbles pop in turn as each user speaks. Accessibility tags flip into place. The orange thread quietly sways.',
      transition: 'The thread pulls tight and tugs a browser window into the frame.',
      text: ['Volante · UX designer', 'user interviews · accessibility · equal access', 'Designing for equal access.'],
    },
    {
      id: 'return', n: 9, stage: 'Back to Orange', start: 70.2, end: 81.9,
      title: 'Returning to Orange with new tools',
      image: 'Two browser windows either side of me. Left: Orange’s public site, where a visitor explores the school and takes a placement test. Right: the internal site, where staff review the result and help the learner find a class.',
      dress: 'Website screens, code brackets, AI sparkles, test cards and review checklists.',
      movement: 'AI sparkles and code brackets orbit my hands as the pages assemble. A question card is answered; a result card appears marked provisional. On the team side, a row moves from “to review” to “talk with learner” to “find a class”.',
      transition: 'Both screens shrink and fly onto my dress.',
      text: ['years later · back to Orange', 'Take the placement test', 'Suggested level · provisional — our team will confirm your class', 'Team site: review · talk with learner · find a class'],
    },
    {
      id: 'close', n: 10, stage: 'Today', start: 81.9, end: 90,
      title: 'The closing image',
      image: 'Every earlier pattern joins one collage around me: childhood pages, phonics letters, lesson slides, research notes, website screens. I stand in the centre holding the small orange shape.',
      dress: 'All of the above, in bands, like a quilt.',
      movement: 'Pieces from every scene fly in and settle into a paper sunburst. The closing line types in, then my name.',
      transition: 'Final hold.',
      text: ['I grew up with Orange.', 'Then I helped it grow in a new way.', 'Parmis Meshgi'],
    },
  ],
  vo: [
    [1.9, 4.6, 'My mother was my first English teacher.'],
    [5.0, 8.2, 'At seven, I sat in her class and filled notebooks with letters.'],
    [9.4, 12.0, 'When I was twelve, she opened her own school.'],
    [12.6, 16.0, 'She named it Orange. It became our family\u2019s story.'],
    [17.4, 20.2, 'At university, I started teaching children at Orange.'],
    [20.8, 25.2, 'Teaching showed me how differently each child learns.'],
    [26.4, 28.8, 'So I trained to teach younger children:'],
    [29.0, 31.6, 'Montessori, where small hands lead\u2026'],
    [32.2, 35.0, '\u2026and phonics, where every letter has a sound.'],
    [36.3, 38.8, 'Then COVID moved my classroom onto a screen.'],
    [39.1, 42.4, 'I worked hard to keep very young children with me online.'],
    [42.7, 44.9, 'And they played along.'],
    [45.3, 48.3, 'But the lesson depended on a screen that wasn\u2019t made for them.'],
    [48.7, 50.6, 'What if it were designed for children?'],
    [50.8, 53.0, 'That question led me to UX design.'],
    [53.5, 55.6, 'So I moved to Canada to study it.'],
    [56.2, 59.5, 'At BrainStation, my capstone was a teaching platform for young children,'],
    [59.9, 62.9, 'built on what children and teachers had shown me.'],
    [63.4, 65.8, 'Then I began my design career at Volante.'],
    [66.2, 69.6, 'I talked with users and designed for equal access.'],
    [70.3, 72.8, 'Years later, I came back to Orange with new skills.'],
    [73.0, 75.4, 'With AI, design and code, I built its website,'],
    [75.5, 78.2, 'where learners explore the school and take a placement test,'],
    [78.3, 81.8, 'and a team site where staff review results and help choose a class.'],
    [82.0, 84.6, 'Every chapter shaped the designer I am.'],
    [85.0, 89.3, 'I grew up with Orange. Then I helped it grow in a new way.'],
  ],
};
